// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0TACtcICIi3DoIhrNSki5urbkt5aFk_k',
    appId: '1:568266338396:web:e42bb62a8dc7d510b47699',
    messagingSenderId: '568266338396',
    projectId: 'fir-mvc-305b6',
    authDomain: 'fir-mvc-305b6.firebaseapp.com',
    storageBucket: 'fir-mvc-305b6.appspot.com',
    measurementId: 'G-06S2WFQETZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp_os6Wlh9Lv0lrP_fgk9Ad8wul8xAPvU',
    appId: '1:568266338396:android:99d458ab9ba2eeaeb47699',
    messagingSenderId: '568266338396',
    projectId: 'fir-mvc-305b6',
    storageBucket: 'fir-mvc-305b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZdtLv5XWKX6z0Bhq6MCZ8MnL9tuNTgc',
    appId: '1:568266338396:ios:eacb473e8aaf6bdfb47699',
    messagingSenderId: '568266338396',
    projectId: 'fir-mvc-305b6',
    storageBucket: 'fir-mvc-305b6.appspot.com',
    iosBundleId: 'com.example.cartexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ZdtLv5XWKX6z0Bhq6MCZ8MnL9tuNTgc',
    appId: '1:568266338396:ios:050fef7919f8404eb47699',
    messagingSenderId: '568266338396',
    projectId: 'fir-mvc-305b6',
    storageBucket: 'fir-mvc-305b6.appspot.com',
    iosBundleId: 'com.example.cartexample.RunnerTests',
  );
}
