// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMydcc-t5TDUu-2Bh3-Joy14w6quBm25A',
    appId: '1:1004624900638:web:8fcd5370a17789813df40f',
    messagingSenderId: '1004624900638',
    projectId: 'cartexample-fd2cf',
    authDomain: 'cartexample-fd2cf.firebaseapp.com',
    storageBucket: 'cartexample-fd2cf.appspot.com',
    measurementId: 'G-M668TY8LLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChA76MuwcbBhFd0Yr9sNMWJx7_onZ5u_k',
    appId: '1:1004624900638:android:e77becf4e16e50363df40f',
    messagingSenderId: '1004624900638',
    projectId: 'cartexample-fd2cf',
    storageBucket: 'cartexample-fd2cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFXEsM0B10r7kZq-Yze94dEs-YRChqJig',
    appId: '1:1004624900638:ios:c03b5efffc4b692b3df40f',
    messagingSenderId: '1004624900638',
    projectId: 'cartexample-fd2cf',
    storageBucket: 'cartexample-fd2cf.appspot.com',
    iosBundleId: 'com.example.cartexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFXEsM0B10r7kZq-Yze94dEs-YRChqJig',
    appId: '1:1004624900638:ios:03309bc1880f23d93df40f',
    messagingSenderId: '1004624900638',
    projectId: 'cartexample-fd2cf',
    storageBucket: 'cartexample-fd2cf.appspot.com',
    iosBundleId: 'com.example.cartexample.RunnerTests',
  );
}
